apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio
  template:
    metadata:
      labels:
        app: microservicio
    spec:
      containers:
        - name: microservicio
          image: 628366968712.dkr.ecr.us-east-1.amazonaws.com/microservice/tfm-microservice:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: microservicio
  namespace: microservices
  labels:
    app: microservicio
spec:
  type: LoadBalancer
  selector:
    app: microservicio
  ports:
    - name: http
      port: 80
      targetPort: 8080