apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: microservicio-monitor
  namespace: monitoring
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: microservicio
  namespaceSelector:
    matchNames:
      - microservices
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s