apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitor-microservices
  namespace: monitoring
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames:
      - microservices
  selector:
    matchExpressions:
      - { key: app, operator: In, values: [microservicio-1, microservicio-2] }
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 5s
