apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitor-microservices
  namespace: monitoring
  labels:
    release: kps
spec:
  selector:
    matchLabels:
      app: monitor-microservices
  namespaceSelector:
    matchNames:
      - microservices
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s