apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio
  template:
    metadata:
      labels:
        app: microservicio
    spec:
      containers:
        - name: microservicio
          image: 628366968712.dkr.ecr.us-east-1.amazonaws.com/microservice/tfm-microservice:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: microservicio
  namespace: microservices
spec:
  type: LoadBalancer
  selector:
    app: microservicio
  ports:
    - port: 80
      targetPort: 8080