apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservicio-2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aroman09/tfm-repository.git
    targetRevision: HEAD
    path: gitops/microservicios/microservicio-2
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
